services:
  web:
    build: .
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    links:
      - db
  db:
    image: mongo:7.0.2
    hostname: "todo_mongodb"
